name: reactive_state_machine
description: A flexible and easy-to-use framework to create reactive hierarchical finite state machines.
version: 0.0.1-dev.1

environment:
  sdk: ^3.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
