name: flutter_reactive_state_machine
description: An extension to `reactive_stat_machine` package to create Listenable state machines for flutter.
repository: https://github.com/AffordantSoftware/reactive_state_machine
version: 0.0.1-dev.1

environment:
  sdk: ^3.1.5

dependencies:
  flutter:
    sdk: flutter
  reactive_state_machine: ^0.0.1-dev.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0